services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./backend:/app
    environment:
      - TZ=${TZ}
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
      - "${STORYBOOK_PORT}:6006"
    volumes:
      - ./frontend:/app
    environment:
      - TZ=${TZ}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_URL=${API_URL}
    depends_on:
      - backend
