# air 設定ファイル
root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "docs"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = ["_test.go"]
  watch_dir = ["internal", "cmd"]
  build_delay = 200

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
